display:
  display-name: "Chatter"
  lore:
    - "&8»&7 Send &cThe grind never stops! &a%required%&7 times"
    - "&8»&7 Completed: &a%current%&7/&a%required%"

xp-gain-methods:
  - trigger: send_message
    multiplier: 1
    filters:
      text:
        - "The grind never stops!"