display:
  display-name: "Ender Stairs"
  lore:
    - "&8»&7 Craft &a%required%&7 end stone brick stairs"
    - "&8»&7 Completed: &a%current%&7/&a%required%"

xp-gain-methods:
  - trigger: craft
    multiplier: 1
    filters:
      items:
        - end_stone_brick_stairs