display:
  display-name: "Glider"
  lore:
    - "&8»&7 Glide &a%required%&7 blocks"
    - "&8»&7 Completed: &a%current%&7/&a%required%"

xp-gain-methods:
  - trigger: move
    multiplier: 1
    conditions:
      - id: is_gliding