display:
  display-name: "Miner"
  lore:
    - "&8»&7 Mine &a%required%&7 diamond ore"
    - "&8»&7 Completed: &a%current%&7/&a%required%"

xp-gain-methods:
  - trigger: mine_block
    multiplier: 1
    filters:
      blocks:
        - "DIAMOND_ORE"
        - "DEEPSLATE_DIAMOND_ORE"
      player_placed: false