display:
  display-name: "Murder Mystery"
  lore:
    - "&8»&7 Kill &a%required%&7 players in PVP"
    - "&8»&7 Completed: &a%current%&7/&a%required%"

xp-gain-methods:
  - trigger: kill
    value: 1
    filters:
      entities:
        - PLAYER