display:
  display-name: "The End?"
  lore:
    - "&8»&7 Visit The End"
    - "&8»&7 Completed: &a%current%&7/&a%required%"

xp-gain-methods:
  - trigger: change_world
    value: 1
    conditions:
      - id: in_world
        args:
          world: world_the_end